export default [
  {
    orderNumber: 446524154,
    name: 'Elite Xt',
    customer: 'Abhi',
    method: 'Visa',
    status: 'inprogress',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
  {
    orderNumber: 454548482,
    name: 'Supplement',
    customer: 'Druvl',
    method: 'Msster',
    status: 'success',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
  {
    orderNumber: 926151,
    name: 'Immune Complex Pack',
    customer: 'Gaurav',
    method: 'Msster',
    status: 'faild',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
  {
    orderNumber: 162565789,
    name: 'Pure whey',
    customer: 'Razat',
    method: 'Msster',
    status: 'success',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
  {
    orderNumber: 636189827,
    name: 'Need O-Carbs',
    customer: 'Robert',
    method: 'Msster',
    status: 'cancelled',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
  {
    orderNumber: 726562026,
    name: 'Need O-Carbs',
    customer: 'Tony',
    method: 'Msster',
    status: 'cancelled',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
  {
    orderNumber: 926151,
    name: 'Immune Complex Pack',
    customer: 'Ankit',
    method: 'Msster',
    status: 'failed',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
  {
    orderNumber: 162565789,
    name: 'Pure whey',
    customer: 'Rohit',
    method: 'Visa',
    status: 'inprogress',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
  {
    orderNumber: 636189827,
    name: 'Need O-Carbs',
    customer: 'Sam',
    method: 'Msster',
    status: 'cancelled',
    totalCost: '$50',
    deliveryAddress: 'NYC USA',
    customerMobile: 8563215775,
    customerEmail: 'razatverma@gmail.com',
  },
];
